name: cadastro_tasks
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.0
  lottie: ^2.6.0
  path: ^1.8.3
  sqflite: ^2.3.0
  image_picker: ^1.0.4
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  path_provider: ^2.1.1
  provider: ^5.0.0
  http: ^1.1.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - 'assets/images/'


